"""
Calculate final scores for EXPRESS-Bench.
Computes C_avg, C_star_avg, E_path, and d_T_avg according to the EXPRESS-Bench evaluation protocol.
"""

import json
import numpy as np
import argparse

def score(results):
    """
    Calculate scores according to the EXPRESS-Bench evaluation protocol.
    
    Args:
        results: List of evaluation results, each containing:
            - EAC: "Your mark: {image_score}, {accuracy_score}"
            - path_len: Actual path length
            - geodesic_distance: Shortest path length (geodesic distance)
            - goal_dis: Distance to goal point
    
    Returns:
        C_avg: Average accuracy score (considering image alignment)
        C_star_avg: Average accuracy score (without considering image alignment)
        E_path: Average score considering path efficiency
        d_T_avg: Average goal distance
    """
    C, C_star, p_path, l_path, d_T = [], [], [], [], []
    
    for result in results:
        if result.get("path_len") != float("inf") and "accuracy_score" in result:

            # "Your mark: {image_score}, {accuracy_score}"
            image_score = result.get("image_alignment_score", 0)
            accuracy_score = result.get("accuracy_score", 1)
            
            # C = image_score * accuracy_score
            # C_star = accuracy_score
            C.append(image_score * accuracy_score)
            C_star.append(accuracy_score)
            p_path.append(result["path_len"])
            l_path.append(result["geodesic_distance"])
        
        if result.get("goal_dis") != float("inf"):
            d_T.append(result["goal_dis"])
    
    C = np.array(C)
    C_star = np.array(C_star)
    p_path = np.array(p_path)
    l_path = np.array(l_path)
    d_T = np.array(d_T) if d_T else np.array([])
    
    # Calculate path weight: l_path / max(p_path, l_path)
    weight_path = l_path / np.maximum(p_path, l_path)
    
    # Calculate metrics (score range 0-5, converted to 0-100)
    C_avg = np.mean(100.0 * (np.clip(C, 0, 5) / 5))
    C_star_avg = np.mean(100.0 * (np.clip(C_star, 0, 5) / 5))
    E_path = np.mean(100.0 * (np.clip(C, 0, 5) / 5) * weight_path)
    d_T_avg = np.mean(d_T) if len(d_T) > 0 else float('inf')
    
    return C_avg, C_star_avg, E_path, d_T_avg

def calculate_scores_by_category(results):
    """Calculate scores by category."""
    categories = {}
    
    for result in results:
        if "accuracy_score" not in result:
            continue
        
        category = result.get("category", "unknown")
        if category not in categories:
            categories[category] = []
        categories[category].append(result)
    
    category_scores = {}
    for category, cat_results in categories.items():
        if cat_results:
            C_avg, C_star_avg, E_path, d_T_avg = score(cat_results)
            category_scores[category] = {
                "C_avg": C_avg,
                "C_star_avg": C_star_avg,
                "E_path": E_path,
                "d_T_avg": d_T_avg,
                "n_questions": len(cat_results)
            }
    
    return category_scores

def main(evaluation_file, output_file=None):
    """
    Main function: read evaluation result file and calculate scores.
    
    Args:
        evaluation_file: Evaluation result file generated by evaluate_express_bench.py
        output_file: Output scores file (optional)
    """
    print(f"Loading evaluation results: {evaluation_file}")
    with open(evaluation_file, 'r', encoding='utf-8') as f:
        results = json.load(f)
    
    print(f"Evaluation results loaded, {len(results)} total results")
    
    # Count valid results
    valid_results = [r for r in results if "accuracy_score" in r]
    print(f"Results: {len(valid_results)}/{len(results)}")
    
    if not valid_results:
        print("Error: No valid evaluation results")
        return
    
    # Calculate overall scores
    print("\n" + "="*50)
    print("Overall Scores:")
    print("="*50)
    C_avg, C_star_avg, E_path, d_T_avg = score(valid_results)
    
    print(f"C_avg (Image alignment x Accuracy): {C_avg:.2f}")
    print(f"C_star_avg (Accuracy only): {C_star_avg:.2f}")
    print(f"E_path (With path efficiency): {E_path:.2f}")
    print(f"d_T_avg (Average goal distance): {d_T_avg:.2f}")
    
    # Calculate scores by category
    print("\n" + "="*50)
    print("Scores by Category:")
    print("="*50)
    category_scores = calculate_scores_by_category(valid_results)
    
    for category, scores in sorted(category_scores.items()):
        print(f"\nCategory: {category} (Questions: {scores['n_questions']})")
        print(f"  C_avg: {scores['C_avg']:.2f}")
        print(f"  C_star_avg: {scores['C_star_avg']:.2f}")
        print(f"  E_path: {scores['E_path']:.2f}")
        print(f"  d_T_avg: {scores['d_T_avg']:.2f}")
    
    # Save results
    output_data = {
        "total": {
            "C_avg": float(C_avg),
            "C_star_avg": float(C_star_avg),
            "E_path": float(E_path),
            "d_T_avg": float(d_T_avg),
            "n_questions": len(valid_results),
            "n_total_results": len(results)
        },
        "by_category": {
            cat: {
                "C_avg": float(scores['C_avg']),
                "C_star_avg": float(scores['C_star_avg']),
                "E_path": float(scores['E_path']),
                "d_T_avg": float(scores['d_T_avg']),
                "n_questions": scores['n_questions']
            }
            for cat, scores in category_scores.items()
        }
    }
    
    if output_file:
        print(f"\nSaving scores to: {output_file}")
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(output_data, f, ensure_ascii=False, indent=2)
    else:
        # Default save in same directory
        import os
        output_file = evaluation_file.replace('.json', '_scores.json')
        print(f"\nSaving scores to: {output_file}")
        with open(output_file, 'w', encoding='utf-8') as f:
            json.dump(output_data, f, ensure_ascii=False, indent=2)
    
    print("\n" + "="*50)
    print("Calculation complete!")
    print("="*50)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Calculate EXPRESS-Bench scores')
    parser.add_argument(
        "--evaluation-file",
        type=str,
        required=True,
        help="Evaluation result file (generated by evaluate_express_bench.py)"
    )
    parser.add_argument(
        "--output-file",
        type=str,
        default=None,
        help="Output scores file (optional, defaults to <evaluation-file>_scores.json)"
    )
    
    args = parser.parse_args()
    
    main(args.evaluation_file, args.output_file)

